services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        volumes:
            - .:/var/www
        networks:
            - laravel-network

    web:
        image: nginx:alpine
        container_name: nginx
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel-network

    db:
        image: mysql:5.7
        container_name: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - laravel-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8081:80"
        environment:
            PMA_HOST: mysql
            PMA_USER: root
            PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        networks:
            - laravel-network

networks:
    laravel-network:
        driver: bridge

volumes:
    db_data:
